import { HotspotRecord, BroadcastAlert, SummaryStats, ScenarioPreset } from '../types';

export const MOCK_SUMMARY: SummaryStats = {
  total_records: 20000,
  critical_zones: 1420,
  high_risk_zones: 3890,
  moderate_zones: 6150,
  low_risk_zones: 8540,
  landslide_events: 534,
  states_monitored: 12,
  last_updated: '2026-09-23T14:30:00Z',
};

export const MOCK_HOTSPOTS: HotspotRecord[] = [
  // MEGHALAYA — East Khasi Hills & West Jaintia
  {
    id: 'HS-ML-01',
    date: '2026-09-23',
    state: 'Meghalaya',
    district: 'East Khasi Hills (Sohra Ridge)',
    latitude: 25.289,
    longitude: 91.734,
    elevation_m: 1480,
    slope_deg: 38.5,
    soil_moisture: 94.2,
    rainfall_24h_mm: 245.0,
    risk_score: 93.4,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 52.1,
    distance_to_road_km: 0.08,
    distance_to_settlement_km: 1.1,
  },
  {
    id: 'HS-ML-02',
    date: '2026-09-23',
    state: 'Meghalaya',
    district: 'West Jaintia Hills (Dawki Pass)',
    latitude: 25.184,
    longitude: 92.012,
    elevation_m: 1120,
    slope_deg: 34.0,
    soil_moisture: 88.5,
    rainfall_24h_mm: 195.4,
    risk_score: 87.2,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 39.8,
    distance_to_road_km: 0.15,
    distance_to_settlement_km: 2.3,
  },

  // ASSAM — Dima Hasao & Karbi Anglong
  {
    id: 'HS-AS-01',
    date: '2026-09-23',
    state: 'Assam',
    district: 'Dima Hasao (Jatinga Valley / NH-27)',
    latitude: 25.122,
    longitude: 93.034,
    elevation_m: 860,
    slope_deg: 36.4,
    soil_moisture: 91.0,
    rainfall_24h_mm: 215.0,
    risk_score: 91.8,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 48.0,
    distance_to_road_km: 0.05,
    distance_to_settlement_km: 1.8,
  },
  {
    id: 'HS-AS-02',
    date: '2026-09-22',
    state: 'Assam',
    district: 'Karbi Anglong (Hamren Escarpment)',
    latitude: 25.845,
    longitude: 92.562,
    elevation_m: 650,
    slope_deg: 24.5,
    soil_moisture: 68.2,
    rainfall_24h_mm: 92.0,
    risk_score: 58.4,
    risk_class: 'HIGH',
    landslide_occurrence: 0,
    displacement_mm: 12.0,
    distance_to_road_km: 0.8,
    distance_to_settlement_km: 4.2,
  },

  // SIKKIM — Gangtok & Mangan
  {
    id: 'HS-SK-01',
    date: '2026-09-23',
    state: 'Sikkim',
    district: 'North Sikkim (Mangan Highway Corridor)',
    latitude: 27.512,
    longitude: 88.541,
    elevation_m: 1950,
    slope_deg: 44.0,
    soil_moisture: 96.0,
    rainfall_24h_mm: 270.0,
    risk_score: 95.2,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 61.2,
    distance_to_road_km: 0.02,
    distance_to_settlement_km: 1.4,
  },
  {
    id: 'HS-SK-02',
    date: '2026-09-23',
    state: 'Sikkim',
    district: 'Gangtok (Pakyong Ridge NH-10)',
    latitude: 27.241,
    longitude: 88.618,
    elevation_m: 1620,
    slope_deg: 35.8,
    soil_moisture: 86.4,
    rainfall_24h_mm: 165.0,
    risk_score: 82.1,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 29.5,
    distance_to_road_km: 0.1,
    distance_to_settlement_km: 0.7,
  },

  // ARUNACHAL PRADESH — Kameng & Tawang Axis
  {
    id: 'HS-AR-01',
    date: '2026-09-23',
    state: 'Arunachal Pradesh',
    district: 'West Kameng (Bhalukpong-Tawang Axis)',
    latitude: 27.018,
    longitude: 92.651,
    elevation_m: 2100,
    slope_deg: 41.2,
    soil_moisture: 90.5,
    rainfall_24h_mm: 198.0,
    risk_score: 89.6,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 44.0,
    distance_to_road_km: 0.04,
    distance_to_settlement_km: 2.1,
  },

  // UTTARAKHAND — Himalayan High Threat Corridors
  {
    id: 'HS-UK-01',
    date: '2026-09-23',
    state: 'Uttarakhand',
    district: 'Chamoli (Joshimath Slump Zone)',
    latitude: 30.556,
    longitude: 79.567,
    elevation_m: 1890,
    slope_deg: 39.0,
    soil_moisture: 91.5,
    rainfall_24h_mm: 185.0,
    risk_score: 92.6,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 54.0,
    distance_to_road_km: 0.05,
    distance_to_settlement_km: 0.3,
  },
  {
    id: 'HS-UK-02',
    date: '2026-09-22',
    state: 'Uttarakhand',
    district: 'Rudraprayag (Kedarnath Valley Road)',
    latitude: 30.485,
    longitude: 78.980,
    elevation_m: 1450,
    slope_deg: 35.5,
    soil_moisture: 84.0,
    rainfall_24h_mm: 140.0,
    risk_score: 81.4,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 33.2,
    distance_to_road_km: 0.1,
    distance_to_settlement_km: 1.2,
  },

  // HIMACHAL PRADESH — Kullu & Shimla Corridors
  {
    id: 'HS-HP-01',
    date: '2026-09-23',
    state: 'Himachal Pradesh',
    district: 'Kullu (Manali Valley Cut / NH-3)',
    latitude: 31.957,
    longitude: 77.109,
    elevation_m: 1720,
    slope_deg: 37.5,
    soil_moisture: 89.0,
    rainfall_24h_mm: 175.0,
    risk_score: 88.5,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 42.0,
    distance_to_road_km: 0.06,
    distance_to_settlement_km: 0.9,
  },
  {
    id: 'HS-HP-02',
    date: '2026-09-22',
    state: 'Himachal Pradesh',
    district: 'Shimla (Sanjauli Escarpment)',
    latitude: 31.104,
    longitude: 77.173,
    elevation_m: 2180,
    slope_deg: 32.0,
    soil_moisture: 76.5,
    rainfall_24h_mm: 115.0,
    risk_score: 71.2,
    risk_class: 'HIGH',
    landslide_occurrence: 0,
    displacement_mm: 19.5,
    distance_to_road_km: 0.15,
    distance_to_settlement_km: 0.4,
  },

  // JAMMU & KASHMIR / LADAKH — Comprehensive Himalayan Stations
  {
    id: 'HS-JK-01',
    date: '2026-09-23',
    state: 'Jammu & Kashmir',
    district: 'Ramban (Panthyal Shooters / NH-44)',
    latitude: 33.242,
    longitude: 75.241,
    elevation_m: 1150,
    slope_deg: 43.0,
    soil_moisture: 87.0,
    rainfall_24h_mm: 160.0,
    risk_score: 90.4,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 49.0,
    distance_to_road_km: 0.02,
    distance_to_settlement_km: 1.5,
  },
  {
    id: 'HS-JK-02',
    date: '2026-09-23',
    state: 'Jammu & Kashmir',
    district: 'Doda (Kishtwar Gorge Highway)',
    latitude: 33.145,
    longitude: 75.541,
    elevation_m: 1380,
    slope_deg: 41.5,
    soil_moisture: 82.5,
    rainfall_24h_mm: 135.0,
    risk_score: 83.2,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 37.0,
    distance_to_road_km: 0.04,
    distance_to_settlement_km: 1.8,
  },
  {
    id: 'HS-JK-03',
    date: '2026-09-22',
    state: 'Jammu & Kashmir',
    district: 'Ganderbal (Sonamarg Glacial Valley)',
    latitude: 34.312,
    longitude: 75.291,
    elevation_m: 2740,
    slope_deg: 38.0,
    soil_moisture: 79.0,
    rainfall_24h_mm: 98.0,
    risk_score: 72.8,
    risk_class: 'HIGH',
    landslide_occurrence: 0,
    displacement_mm: 21.0,
    distance_to_road_km: 0.1,
    distance_to_settlement_km: 2.1,
  },
  {
    id: 'HS-JK-04',
    date: '2026-09-22',
    state: 'Jammu & Kashmir',
    district: 'Poonch (Mughal Road Peer Ki Gali)',
    latitude: 33.612,
    longitude: 74.520,
    elevation_m: 2950,
    slope_deg: 36.5,
    soil_moisture: 74.0,
    rainfall_24h_mm: 85.0,
    risk_score: 68.5,
    risk_class: 'HIGH',
    landslide_occurrence: 0,
    displacement_mm: 17.5,
    distance_to_road_km: 0.08,
    distance_to_settlement_km: 3.2,
  },
  {
    id: 'HS-LK-01',
    date: '2026-09-21',
    state: 'Ladakh',
    district: 'Kargil (Zojila Approach Scree Slope)',
    latitude: 34.281,
    longitude: 75.498,
    elevation_m: 3520,
    slope_deg: 46.0,
    soil_moisture: 65.0,
    rainfall_24h_mm: 68.0,
    risk_score: 69.8,
    risk_class: 'HIGH',
    landslide_occurrence: 0,
    displacement_mm: 22.0,
    distance_to_road_km: 0.05,
    distance_to_settlement_km: 4.8,
  },
  {
    id: 'HS-LK-02',
    date: '2026-09-20',
    state: 'Ladakh',
    district: 'Leh (Khardung La Northern Permafrost Ridge)',
    latitude: 34.279,
    longitude: 77.604,
    elevation_m: 4890,
    slope_deg: 39.0,
    soil_moisture: 52.0,
    rainfall_24h_mm: 45.0,
    risk_score: 52.4,
    risk_class: 'MODERATE',
    landslide_occurrence: 0,
    displacement_mm: 12.0,
    distance_to_road_km: 0.04,
    distance_to_settlement_km: 6.5,
  },

  // WESTERN GHATS — Kerala (Wayanad, Idukki) & Maharashtra
  {
    id: 'HS-KL-01',
    date: '2026-09-23',
    state: 'Kerala',
    district: 'Wayanad (Meppadi-Chooralmala Ridge)',
    latitude: 11.556,
    longitude: 76.128,
    elevation_m: 980,
    slope_deg: 38.0,
    soil_moisture: 97.5,
    rainfall_24h_mm: 310.0,
    risk_score: 96.8,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 68.0,
    distance_to_road_km: 0.05,
    distance_to_settlement_km: 0.6,
  },
  {
    id: 'HS-KL-02',
    date: '2026-09-22',
    state: 'Kerala',
    district: 'Idukki (Munnar Gap Road Cut)',
    latitude: 10.088,
    longitude: 77.059,
    elevation_m: 1530,
    slope_deg: 36.0,
    soil_moisture: 89.0,
    rainfall_24h_mm: 190.0,
    risk_score: 85.2,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 34.0,
    distance_to_road_km: 0.08,
    distance_to_settlement_km: 1.1,
  },
  {
    id: 'HS-MH-01',
    date: '2026-09-22',
    state: 'Maharashtra',
    district: 'Raigad (Varandha Ghats Pass)',
    latitude: 18.236,
    longitude: 73.442,
    elevation_m: 780,
    slope_deg: 34.5,
    soil_moisture: 85.0,
    rainfall_24h_mm: 170.0,
    risk_score: 79.5,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 27.5,
    distance_to_road_km: 0.04,
    distance_to_settlement_km: 2.2,
  },

  // MIZORAM, NAGALAND, MANIPUR, TRIPURA
  {
    id: 'HS-MZ-01',
    date: '2026-09-23',
    state: 'Mizoram',
    district: 'Aizawl (Ramhlun North Escarpment)',
    latitude: 23.742,
    longitude: 92.721,
    elevation_m: 1150,
    slope_deg: 37.0,
    soil_moisture: 87.8,
    rainfall_24h_mm: 160.0,
    risk_score: 84.7,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 36.5,
    distance_to_road_km: 0.09,
    distance_to_settlement_km: 0.4,
  },
  {
    id: 'HS-NL-01',
    date: '2026-09-23',
    state: 'Nagaland',
    district: 'Kohima (Dzükou Bypass / NH-29)',
    latitude: 25.670,
    longitude: 94.108,
    elevation_m: 1440,
    slope_deg: 35.0,
    soil_moisture: 89.2,
    rainfall_24h_mm: 182.0,
    risk_score: 86.4,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 41.0,
    distance_to_road_km: 0.05,
    distance_to_settlement_km: 1.2,
  },
  {
    id: 'HS-MN-01',
    date: '2026-09-23',
    state: 'Manipur',
    district: 'Tamenglong (Barak River Terraces)',
    latitude: 24.985,
    longitude: 93.492,
    elevation_m: 1260,
    slope_deg: 33.5,
    soil_moisture: 85.0,
    rainfall_24h_mm: 154.0,
    risk_score: 81.3,
    risk_class: 'CRITICAL',
    landslide_occurrence: 1,
    displacement_mm: 32.0,
    distance_to_road_km: 0.15,
    distance_to_settlement_km: 1.5,
  },
  {
    id: 'HS-TR-01',
    date: '2026-09-22',
    state: 'Tripura',
    district: 'North Tripura (Jampui Hills Ridge)',
    latitude: 23.955,
    longitude: 92.278,
    elevation_m: 930,
    slope_deg: 25.0,
    soil_moisture: 69.5,
    rainfall_24h_mm: 88.0,
    risk_score: 55.7,
    risk_class: 'HIGH',
    landslide_occurrence: 0,
    displacement_mm: 11.2,
    distance_to_road_km: 0.6,
    distance_to_settlement_km: 2.0,
  }
];

export const MOCK_BROADCASTS: BroadcastAlert[] = [
  {
    broadcast_id: 'BCAST-2026-KL-0923',
    state: 'Kerala',
    district: 'Wayanad (Meppadi-Chooralmala)',
    latitude: 11.556,
    longitude: 76.128,
    risk_score: 96.8,
    risk_class: 'CRITICAL',
    audience: 'NDRF 4th Bn, KSDMA & District Emergency Operations',
    severity: 'Critical Red Alert',
    message: 'RED LEVEL BULLETIN: Extraordinary 24h precipitation exceeding 310mm on saturated slope mantle (97.5%). Active InSAR shear creep > 68mm. Immediate evacuation order of Chooralmala-Mundakkai river valley and emergency halt to downhill vehicular passage.',
    timestamp: '2026-09-23T14:40:00Z',
    status: 'Delivered',
    advisory_code: 'SANKET-RED-904',
  },
  {
    broadcast_id: 'BCAST-2026-AS-0923',
    state: 'Assam',
    district: 'Dima Hasao (Jatinga & Haflong)',
    latitude: 25.122,
    longitude: 93.034,
    risk_score: 91.8,
    risk_class: 'CRITICAL',
    audience: 'NDRF, SDMA & BRO Taskforce 83',
    severity: 'Critical Hazard',
    message: 'RED LEVEL BULLETIN: 24h precipitation exceeded 215mm with InSAR displacement creep > 48mm along NH-27 arterial corridor. High likelihood of catastrophic debris slide. Enact immediate heavy vehicle diversions and prime disaster quick-response teams.',
    timestamp: '2026-09-23T14:15:00Z',
    status: 'Delivered',
    advisory_code: 'SANKET-RED-831',
  },
  {
    broadcast_id: 'BCAST-2026-UK-0923',
    state: 'Uttarakhand',
    district: 'Chamoli (Joshimath-Badrinath Corridor)',
    latitude: 30.556,
    longitude: 79.567,
    risk_score: 92.6,
    risk_class: 'CRITICAL',
    audience: 'BRO Shivalik, DDMA Chamoli & SDRF',
    severity: 'Critical Hazard',
    message: 'URGENT RED BULLETIN: Active toe erosion by Alaknanda river combined with intense cloudburst precipitation. Suspend pilgrim traffic along NH-07 and inspect retaining walls.',
    timestamp: '2026-09-23T13:55:00Z',
    status: 'Delivered',
    advisory_code: 'SANKET-RED-822',
  },
  {
    broadcast_id: 'BCAST-2026-ML-0923',
    state: 'Meghalaya',
    district: 'East Khasi Hills (Sohra Ridge)',
    latitude: 25.289,
    longitude: 91.734,
    risk_score: 93.4,
    risk_class: 'CRITICAL',
    audience: 'District Magistrate & State Emergency Operations',
    severity: 'Critical Hazard',
    message: 'EXTREME SATURATION WARNING: Soil column saturation at 94.2% following 245mm torrential rainfall. Slopes steeper than 35° entering critical shear threshold. Pre-emptive evacuation order advised for settlements downhill of Sohra Rim.',
    timestamp: '2026-09-23T13:40:00Z',
    status: 'Delivered',
    advisory_code: 'SANKET-RED-829',
  },
  {
    broadcast_id: 'BCAST-2026-JK-0922',
    state: 'Jammu & Kashmir',
    district: 'Ramban (Panthyal Shooters / NH-44)',
    latitude: 33.242,
    longitude: 75.241,
    risk_score: 90.4,
    risk_class: 'CRITICAL',
    audience: 'Traffic Police NH-44, BRO Beacon & District Police',
    severity: 'Critical Hazard',
    message: 'HIGHWAY CLOSURE ADVISORY: Continuous stone shooting and mudslides reported at Panthyal and Mehar. Halt all vehicular movement between Udhampur and Banihal until daylight clearance.',
    timestamp: '2026-09-22T22:30:00Z',
    status: 'Delivered',
    advisory_code: 'SANKET-RED-818',
  },
];

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: 'preset_wayanad_extreme',
    label: 'Wayanad Western Ghats — Torrential Cloudburst',
    location: 'Chooralmala-Meppadi, Kerala',
    state: 'Kerala',
    elevation: 980,
    slopeDeg: 38.0,
    soilType: 'Lateritic Soil over Charnockite Basement',
    description: 'Catastrophic debris flow driven by extreme 310mm antecedent rainfall on steep saturated tea-estate slopes.',
    threatLevel: 'CRITICAL',
    features: {
      latitude: 11.556,
      longitude: 76.128,
      rainfall_24h_mm: 310.0,
      rainfall_72h_mm: 580.0,
      rainfall_7d_mm: 890.0,
      rainfall_intensity_3h_mm: 64.0,
      rainfall_anomaly_pct: 220.0,
      elevation_m: 980.0,
      slope_deg: 38.0,
      aspect_deg: 240.0,
      curvature: 0.42,
      soil_moisture: 0.98,
      clay_pct: 38.0,
      ndvi: 0.72,
      geology_risk_index: 0.94,
      displacement_mm: 68.0,
      historical_landslide_count: 7,
      distance_to_road_km: 0.05,
      distance_to_settlement_km: 0.6,
      infrastructure_exposure_index: 89.0,
    },
  },
  {
    id: 'preset_joshimath_subsidence',
    label: 'Chamoli Himalayas — Active Toe Slumping',
    location: 'Joshimath-Alaknanda Gorge, Uttarakhand',
    state: 'Uttarakhand',
    elevation: 1890,
    slopeDeg: 39.0,
    soilType: 'Glacial Moraine & Main Central Thrust Sheared Gneiss',
    description: 'Steep river valley toe-cutting coupled with monsoon infiltration and active tectonic subsidence.',
    threatLevel: 'CRITICAL',
    features: {
      latitude: 30.556,
      longitude: 79.567,
      rainfall_24h_mm: 185.0,
      rainfall_72h_mm: 340.0,
      rainfall_7d_mm: 490.0,
      rainfall_intensity_3h_mm: 38.0,
      rainfall_anomaly_pct: 140.0,
      elevation_m: 1890.0,
      slope_deg: 39.0,
      aspect_deg: 180.0,
      curvature: 0.32,
      soil_moisture: 0.92,
      clay_pct: 24.0,
      ndvi: 0.42,
      geology_risk_index: 0.96,
      displacement_mm: 54.0,
      historical_landslide_count: 11,
      distance_to_road_km: 0.05,
      distance_to_settlement_km: 0.3,
      infrastructure_exposure_index: 92.0,
    },
  },
  {
    id: 'preset_cherrapunji_extreme',
    label: 'East Khasi Hills — Torrential Monsoon Escarpment',
    location: 'Sohra Rim, Meghalaya',
    state: 'Meghalaya',
    elevation: 1480,
    slopeDeg: 38.5,
    soilType: 'Residual Humus over Weathered Sandstone',
    description: 'Extreme multi-day precipitation triggering complete soil saturation and high shear failure along steep escarpments.',
    threatLevel: 'CRITICAL',
    features: {
      latitude: 25.289,
      longitude: 91.734,
      rainfall_24h_mm: 245.0,
      rainfall_72h_mm: 520.0,
      rainfall_7d_mm: 810.0,
      rainfall_intensity_3h_mm: 52.0,
      rainfall_anomaly_pct: 195.0,
      elevation_m: 1480.0,
      slope_deg: 38.5,
      aspect_deg: 175.0,
      curvature: 0.35,
      soil_moisture: 0.94,
      clay_pct: 36.0,
      ndvi: 0.65,
      geology_risk_index: 0.88,
      displacement_mm: 52.1,
      historical_landslide_count: 9,
      distance_to_road_km: 0.08,
      distance_to_settlement_km: 1.1,
      infrastructure_exposure_index: 82.0,
    },
  },
  {
    id: 'preset_ramban_nh44',
    label: 'Pir Panjal Range — Arterial Highway Rockfall',
    location: 'Ramban-Panthyal, Jammu & Kashmir',
    state: 'Jammu & Kashmir',
    elevation: 1150,
    slopeDeg: 43.0,
    soilType: 'Fractured Quartzite & Shale Colluvium',
    description: 'Steep hill cut with unstable jointing prone to shooting stones and sudden debris slips along NH-44.',
    threatLevel: 'CRITICAL',
    features: {
      latitude: 33.242,
      longitude: 75.241,
      rainfall_24h_mm: 160.0,
      rainfall_72h_mm: 310.0,
      rainfall_7d_mm: 440.0,
      rainfall_intensity_3h_mm: 35.0,
      rainfall_anomaly_pct: 130.0,
      elevation_m: 1150.0,
      slope_deg: 43.0,
      aspect_deg: 160.0,
      curvature: 0.25,
      soil_moisture: 0.87,
      clay_pct: 22.0,
      ndvi: 0.38,
      geology_risk_index: 0.95,
      displacement_mm: 49.0,
      historical_landslide_count: 15,
      distance_to_road_km: 0.02,
      distance_to_settlement_km: 1.5,
      infrastructure_exposure_index: 96.0,
    },
  },
  {
    id: 'preset_dima_hasao_creep',
    label: 'Dima Hasao Corridor — Heavy Transport Creep',
    location: 'Jatinga Valley, Assam',
    state: 'Assam',
    elevation: 860,
    slopeDeg: 36.4,
    soilType: 'Fractured Shale & Saturated Silt Clay',
    description: 'Active tectonic fault zone intersected by NH-27 highway and broad-gauge mountain railway with active slope creep.',
    threatLevel: 'CRITICAL',
    features: {
      latitude: 25.122,
      longitude: 93.034,
      rainfall_24h_mm: 215.0,
      rainfall_72h_mm: 380.0,
      rainfall_7d_mm: 560.0,
      rainfall_intensity_3h_mm: 42.0,
      rainfall_anomaly_pct: 165.0,
      elevation_m: 860.0,
      slope_deg: 36.4,
      aspect_deg: 215.0,
      curvature: 0.28,
      soil_moisture: 0.91,
      clay_pct: 42.0,
      ndvi: 0.52,
      geology_risk_index: 0.92,
      displacement_mm: 48.0,
      historical_landslide_count: 12,
      distance_to_road_km: 0.05,
      distance_to_settlement_km: 1.8,
      infrastructure_exposure_index: 94.0,
    },
  },
  {
    id: 'preset_stable_valley',
    label: 'Brahmaputra Piedmont — Stable Alluvial Valley',
    location: 'Guwahati Outskirts, Assam',
    state: 'Assam',
    elevation: 95,
    slopeDeg: 6.2,
    soilType: 'Dense Consolidated Alluvial Sand & Clay',
    description: 'Low-gradient valley terrain with robust drainage, zero displacement, and stable soil shear parameters.',
    threatLevel: 'LOW',
    features: {
      latitude: 26.144,
      longitude: 91.736,
      rainfall_24h_mm: 18.0,
      rainfall_72h_mm: 35.0,
      rainfall_7d_mm: 65.0,
      rainfall_intensity_3h_mm: 4.0,
      rainfall_anomaly_pct: -15.0,
      elevation_m: 95.0,
      slope_deg: 6.2,
      aspect_deg: 90.0,
      curvature: -0.02,
      soil_moisture: 0.32,
      clay_pct: 18.0,
      ndvi: 0.45,
      geology_risk_index: 0.12,
      displacement_mm: 0.2,
      historical_landslide_count: 0,
      distance_to_road_km: 0.05,
      distance_to_settlement_km: 0.2,
      infrastructure_exposure_index: 15.0,
    },
  },
];

export const MOCK_HISTORICAL_DATA = [
  { year: '2018', events: 42, avgRainfall: 1850, criticalZones: 110 },
  { year: '2019', events: 58, avgRainfall: 2100, criticalZones: 145 },
  { year: '2020', events: 64, avgRainfall: 2280, criticalZones: 180 },
  { year: '2021', events: 72, avgRainfall: 2420, criticalZones: 215 },
  { year: '2022', events: 96, avgRainfall: 2890, criticalZones: 310 },
  { year: '2023', events: 88, avgRainfall: 2650, criticalZones: 280 },
  { year: '2024', events: 104, avgRainfall: 3120, criticalZones: 360 },
  { year: '2025', events: 112, avgRainfall: 3290, criticalZones: 395 },
];

export const MOCK_STATE_STATISTICS = [
  { state: 'Assam', totalHotspots: 4120, critical: 320, high: 880, moderate: 1420, low: 1500, events: 142 },
  { state: 'Meghalaya', totalHotspots: 3240, critical: 410, high: 910, moderate: 1100, low: 820, events: 128 },
  { state: 'Uttarakhand', totalHotspots: 2890, critical: 380, high: 820, moderate: 980, low: 710, events: 115 },
  { state: 'Himachal Pradesh', totalHotspots: 2740, critical: 340, high: 790, moderate: 920, low: 690, events: 98 },
  { state: 'Kerala', totalHotspots: 2450, critical: 390, high: 710, moderate: 780, low: 570, events: 112 },
  { state: 'Sikkim', totalHotspots: 2650, critical: 365, high: 740, moderate: 850, low: 695, events: 105 },
  { state: 'Arunachal Pradesh', totalHotspots: 3890, critical: 240, high: 710, moderate: 1340, low: 1600, events: 78 },
  { state: 'Jammu & Kashmir', totalHotspots: 2150, critical: 260, high: 590, moderate: 710, low: 590, events: 72 },
  { state: 'Mizoram', totalHotspots: 2180, critical: 180, high: 520, moderate: 790, low: 690, events: 62 },
  { state: 'Nagaland', totalHotspots: 1840, critical: 120, high: 430, moderate: 650, low: 640, events: 44 },
  { state: 'Manipur', totalHotspots: 1560, critical: 95, high: 360, moderate: 580, low: 525, events: 38 },
  { state: 'Maharashtra', totalHotspots: 1280, critical: 85, high: 290, moderate: 480, low: 425, events: 29 },
];
